---
version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - unused
