---
run:
  timeout: 5m

linters:
  disable:
    - errcheck  # Too noisy for initial release
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Ignore unused functions in test files
    - path: _test\.go
      linters:
        - unused
